travellerApp:
  image: tomcat:8.0-jre8
  links:
    - travellerElasticSearch:elastic-search.darkmane.me
    - travellerDb:mongo.darkmane.me
travellerDb:
  image: mongo:3.1
  ports:
    - "27017:27017"
    - "28017:28017"
  expose:
    - "27017"
    - "28017"
travellerElasticSearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"
  expose:
    - "9200"
    - "9300"
  volumes:
    - elasticsearch:/data
travellerdebug:
  build: .
  dockerfile: Dockerfile-debug
  ports:
    - "8080:8080"
    - "8000:8000"
  volumes:
    - ./target:/code
  links:
    - travellerElasticSearch:elastic-search.darkmane.me
    - travellerDb:mongo.darkmane.me
