package com.ffe.traveller.util;

//
//  DiceGenerator.java
//  CthuluCharGen
//
//  Created by Mark Knights on 29/04/07.
//  Copyright 2007 One Stage Before. All rights reserved.
//

import java.util.Random;

public class DiceGenerator {
    static Random generator;
    static final int sides = 6;

    /**
     * @param numRolls
     * @param numDice
     * @return int[]
     * <p/>
     * Used to create a bulk number of similar dice rolls at once.
     * Method returns an array of length numRolls which is made up of
     * totals of the numDice of numSides rolls generated by a Random
     * generator.
     */
    static public int rollDice(int numRolls, int numDice) {

        return rollDiceWithModifier(numDice, 0);
    }

    /**
     * @param numDice
     * @param modifier
     * @return int[]
     * <p/>
     * Used to create a bulk number of similar dice rolls at once that
     * are modified by adding the parameter modifier. Method returns an
     * array of length numRolls which is made up of totals of the
     * numDice of numSides rolls generated by a Random generator.
     */
    static public int rollDiceWithModifier(int numDice, int modifier) {
        int result = 0;
        if (generator == null) {
            generator = new Random();
        }

        for (int i = 0; i < numDice; i++) {
            result = result
                    + (Math.abs(generator.nextInt()) % sides + 1);
        }
        result += (result + modifier);

        return result;
    }

    /**
     * @param numRolls
     * @param numDice
     * @param modifier
     * @return int[]
     * <p/>
     * Used to create a bulk number of similar dice rolls at once that
     * are modified by adding the parameter modifier. Method returns an
     * array of length numRolls which is made up of totals of the
     * numDice of numSides rolls generated by a Random generator.
     */
    static public int[] rollDiceWithModifierArray(int numRolls, int numDice, int modifier) {
        int[] resultArray = new int[numRolls];
        int result;
        if (generator == null) {
            generator = new Random();
        }
        for (int j = 0; j < numRolls; j++) {
            result = 0;
            for (int i = 0; i < numDice; i++) {
                result = result
                        + (Math.abs(generator.nextInt()) % sides + 1);
            }
            resultArray[j] = result + modifier;
        }

        return resultArray;
    }

    /**
     * @param numDice
     * @return int
     * <p/>
     * Returns the number of dice rolled is the same as numDice.
     */
    static public int rollDice(int numDice) {
        return rollDiceWithModifier(numDice, 0);
    }


    static public int roll() {
        return rollDice(2);
    }

    static public int rollDiceInRange(int numDice, int modifier, int lower, int upper) {

        int result = rollDiceWithModifier(numDice, modifier);

        while (result < lower || result > upper) {
            result = rollDiceWithModifier(numDice, modifier);
        }

        return result;
    }
}
